# NumPy

In [ ]:
from numpy import *

In [3]:
a = array([2, 3, 4])
# Массивы содержат только данные одного типа

In [6]:
print(a)
a

[2 3 4]


array([2, 3, 4])

In [7]:
a.ndim # Размерность массива (одномерный, двумерный и т.д.)

1

In [8]:
a.shape # Размеры массива (число строк, столбцов и т.д. - число элементов по каждой размерности)

(3,)

In [11]:
b = array([(1.5, 2, 3), (4, 5, 6)]) # Создание двумерного массива

In [12]:
print(b)

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
b.size # Общее количество элементов

6

In [16]:
# Создание нулевого массива
z = zeros((3, 2)) # 3, 2 помещаются в дополнительные скобки, чтобы представлять из себя объект

In [17]:
z

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [19]:
arange(10, 30, 5) # Функция аналогична функции range, но возвращает массив
# параметры: начальное значение, конечное значение, шаг

array([10, 15, 20, 25])

In [21]:
linspace(0, 2, 9) # Генерирует 9 чисел на отрезке от 0 до 2 с равным шагом
# Начало интервала, конец интервала, количество необходимых точек на интервале (включая граниы)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [22]:
# Превратим одномерный массив в двумерный
b = arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [23]:
a = array([10, 20, 30])
b = arange(3)
print(a)
print(b)

[10 20 30]
[0 1 2]


In [24]:
# Арифметические операции на массиваз выполняются поэлементно
print(a + b)
print(a - b)

[10 21 32]
[10 19 28]


In [25]:
print(a**2)

[100 400 900]


In [26]:
2 * sin(a)

array([-1.08804222,  1.8258905 , -1.97606325])

In [27]:
a < 20

array([ True, False, False], dtype=bool)